baseurl = "/"
languageCode = "en-us"
title = "Kim Sellis Yoga"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true


[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Site for sharing everything I'm doing with yoga."
copyright = "Copyright © 2018-2019 Kim Sellis"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "example"
email = "you@example.com"
linkedin = ""
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false